//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSubstitute.Analyzers.CSharp {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NSubstitute.Analyzers.CSharp.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NonVirtualSetupSpecificationMessageFormat {
            get {
                return ResourceManager.GetString("NonVirtualSetupSpecificationMessageFormat", resourceCulture);
            }
        }
        
        internal static string SubstituteForInternalMemberMessageFormat {
            get {
                return ResourceManager.GetString("SubstituteForInternalMemberMessageFormat", resourceCulture);
            }
        }
        
        internal static string NonVirtualReceivedSetupSpecificationMessageFormat {
            get {
                return ResourceManager.GetString("NonVirtualReceivedSetupSpecificationMessageFormat", resourceCulture);
            }
        }
        
        internal static string NonVirtualWhenSetupSpecificationMessageFormat {
            get {
                return ResourceManager.GetString("NonVirtualWhenSetupSpecificationMessageFormat", resourceCulture);
            }
        }
        
        internal static string NonVirtualReceivedInOrderSetupSpecificationMessageFormat {
            get {
                return ResourceManager.GetString("NonVirtualReceivedInOrderSetupSpecificationMessageFormat", resourceCulture);
            }
        }
        
        internal static string ReEntrantSubstituteCallMessageFormat {
            get {
                return ResourceManager.GetString("ReEntrantSubstituteCallMessageFormat", resourceCulture);
            }
        }
        
        internal static string InternalSetupSpecificationMessageFormat {
            get {
                return ResourceManager.GetString("InternalSetupSpecificationMessageFormat", resourceCulture);
            }
        }
    }
}
