//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSubstitute.Analyzers.CSharp {
    using System;
    using System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NSubstitute.Analyzers.CSharp.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Non-virtual members can not be intercepted..
        /// </summary>
        public static string NonVirtualSetupSpecificationDescription {
            get {
                return ResourceManager.GetString("NonVirtualSetupSpecificationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Member {0} can not be intercepted. Only interface members and virtual, overriding, and abstract members can be intercepted..
        /// </summary>
        public static string NonVirtualSetupSpecificationMessageFormat {
            get {
                return ResourceManager.GetString("NonVirtualSetupSpecificationMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Non-virtual setup specification..
        /// </summary>
        public static string NonVirtualSetupSpecificationTitle {
            get {
                return ResourceManager.GetString("NonVirtualSetupSpecificationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Constructor parameters count mismatch..
        /// </summary>
        public static string SubstituteForConstructorParametersMismatchDescription {
            get {
                return ResourceManager.GetString("SubstituteForConstructorParametersMismatchDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Constructor parameters count mismatch..
        /// </summary>
        public static string SubstituteForConstructorParametersMismatchMessageFormat {
            get {
                return ResourceManager.GetString("SubstituteForConstructorParametersMismatchMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Constructor parameters count mismatch..
        /// </summary>
        public static string SubstituteForConstructorParametersMismatchTitle {
            get {
                return ResourceManager.GetString("SubstituteForConstructorParametersMismatchTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Substitute for internal member..
        /// </summary>
        public static string SubstituteForInternalMemberDescription {
            get {
                return ResourceManager.GetString("SubstituteForInternalMemberDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Substitute for internal member..
        /// </summary>
        public static string SubstituteForInternalMemberMessageFormat {
            get {
                return ResourceManager.GetString("SubstituteForInternalMemberMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Substitute for internal member..
        /// </summary>
        public static string SubstituteForInternalMemberTitle {
            get {
                return ResourceManager.GetString("SubstituteForInternalMemberTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Can only substitute for parts of classes, not interfaces or delegates..
        /// </summary>
        public static string SubstituteForPartsOfUsedForInterfaceDescription {
            get {
                return ResourceManager.GetString("SubstituteForPartsOfUsedForInterfaceDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Can only substitute for parts of classes, not interfaces or delegates..
        /// </summary>
        public static string SubstituteForPartsOfUsedForInterfaceMessageFormat {
            get {
                return ResourceManager.GetString("SubstituteForPartsOfUsedForInterfaceMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Substitute.ForPartsOf used for interface..
        /// </summary>
        public static string SubstituteForPartsOfUsedForInterfaceTitle {
            get {
                return ResourceManager.GetString("SubstituteForPartsOfUsedForInterfaceTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Missing parameterless constructor..
        /// </summary>
        public static string SubstituteForWithoutAccessibleConstructorDescription {
            get {
                return ResourceManager.GetString("SubstituteForWithoutAccessibleConstructorDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Missing parameterless constructor..
        /// </summary>
        public static string SubstituteForWithoutAccessibleConstructorMessageFormat {
            get {
                return ResourceManager.GetString("SubstituteForWithoutAccessibleConstructorMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Missing parameterless constructor..
        /// </summary>
        public static string SubstituteForWithoutAccessibleConstructorTitle {
            get {
                return ResourceManager.GetString("SubstituteForWithoutAccessibleConstructorTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unused received check..
        /// </summary>
        public static string UnusedReceivedDescription {
            get {
                return ResourceManager.GetString("UnusedReceivedDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unused received check..
        /// </summary>
        public static string UnusedReceivedMessageFormat {
            get {
                return ResourceManager.GetString("UnusedReceivedMessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Received check..
        /// </summary>
        public static string UnusedReceivedTitle {
            get {
                return ResourceManager.GetString("UnusedReceivedTitle", resourceCulture);
            }
        }
    }
}
