//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

namespace NSubstitute.Analyzers.Shared {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("NSubstitute.Analyzers.Shared.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NonVirtualSetupSpecificationDescription {
            get {
                return ResourceManager.GetString("NonVirtualSetupSpecificationDescription", resourceCulture);
            }
        }
        
        internal static string NonVirtualSetupSpecificationTitle {
            get {
                return ResourceManager.GetString("NonVirtualSetupSpecificationTitle", resourceCulture);
            }
        }
        
        internal static string InternalSetupSpecificationDescription {
            get {
                return ResourceManager.GetString("InternalSetupSpecificationDescription", resourceCulture);
            }
        }
        
        internal static string InternalSetupSpecificationTitle {
            get {
                return ResourceManager.GetString("InternalSetupSpecificationTitle", resourceCulture);
            }
        }
        
        internal static string UnusedReceivedDescription {
            get {
                return ResourceManager.GetString("UnusedReceivedDescription", resourceCulture);
            }
        }
        
        internal static string UnusedReceivedMessageFormat {
            get {
                return ResourceManager.GetString("UnusedReceivedMessageFormat", resourceCulture);
            }
        }
        
        internal static string UnusedReceivedTitle {
            get {
                return ResourceManager.GetString("UnusedReceivedTitle", resourceCulture);
            }
        }
        
        internal static string UnusedReceivedForOrdinaryMethodDescription {
            get {
                return ResourceManager.GetString("UnusedReceivedForOrdinaryMethodDescription", resourceCulture);
            }
        }
        
        internal static string UnusedReceivedForOrdinaryMethodMessageFormat {
            get {
                return ResourceManager.GetString("UnusedReceivedForOrdinaryMethodMessageFormat", resourceCulture);
            }
        }
        
        internal static string UnusedReceivedForOrdinaryMethodTitle {
            get {
                return ResourceManager.GetString("UnusedReceivedForOrdinaryMethodTitle", resourceCulture);
            }
        }
        
        internal static string PartialSubstituteForUnsupportedTypeDescription {
            get {
                return ResourceManager.GetString("PartialSubstituteForUnsupportedTypeDescription", resourceCulture);
            }
        }
        
        internal static string PartialSubstituteForUnsupportedTypeMessageFormat {
            get {
                return ResourceManager.GetString("PartialSubstituteForUnsupportedTypeMessageFormat", resourceCulture);
            }
        }
        
        internal static string PartialSubstituteForUnsupportedTypeTitle {
            get {
                return ResourceManager.GetString("PartialSubstituteForUnsupportedTypeTitle", resourceCulture);
            }
        }
        
        internal static string SubstituteForWithoutAccessibleConstructorDescription {
            get {
                return ResourceManager.GetString("SubstituteForWithoutAccessibleConstructorDescription", resourceCulture);
            }
        }
        
        internal static string SubstituteForWithoutAccessibleConstructorMessageFormat {
            get {
                return ResourceManager.GetString("SubstituteForWithoutAccessibleConstructorMessageFormat", resourceCulture);
            }
        }
        
        internal static string SubstituteForWithoutAccessibleConstructorTitle {
            get {
                return ResourceManager.GetString("SubstituteForWithoutAccessibleConstructorTitle", resourceCulture);
            }
        }
        
        internal static string SubstituteForConstructorParametersMismatchDescription {
            get {
                return ResourceManager.GetString("SubstituteForConstructorParametersMismatchDescription", resourceCulture);
            }
        }
        
        internal static string SubstituteForConstructorParametersMismatchMessageFormat {
            get {
                return ResourceManager.GetString("SubstituteForConstructorParametersMismatchMessageFormat", resourceCulture);
            }
        }
        
        internal static string SubstituteForConstructorParametersMismatchTitle {
            get {
                return ResourceManager.GetString("SubstituteForConstructorParametersMismatchTitle", resourceCulture);
            }
        }
        
        internal static string SubstituteForInternalMemberDescription {
            get {
                return ResourceManager.GetString("SubstituteForInternalMemberDescription", resourceCulture);
            }
        }
        
        internal static string SubstituteForInternalMemberTitle {
            get {
                return ResourceManager.GetString("SubstituteForInternalMemberTitle", resourceCulture);
            }
        }
        
        internal static string SubstituteConstructorMismatchDescription {
            get {
                return ResourceManager.GetString("SubstituteConstructorMismatchDescription", resourceCulture);
            }
        }
        
        internal static string SubstituteConstructorMismatchMessageFormat {
            get {
                return ResourceManager.GetString("SubstituteConstructorMismatchMessageFormat", resourceCulture);
            }
        }
        
        internal static string SubstituteConstructorMismatchTitle {
            get {
                return ResourceManager.GetString("SubstituteConstructorMismatchTitle", resourceCulture);
            }
        }
        
        internal static string SubstituteMultipleClassesDescription {
            get {
                return ResourceManager.GetString("SubstituteMultipleClassesDescription", resourceCulture);
            }
        }
        
        internal static string SubstituteMultipleClassesMessageFormat {
            get {
                return ResourceManager.GetString("SubstituteMultipleClassesMessageFormat", resourceCulture);
            }
        }
        
        internal static string SubstituteMultipleClassesTitle {
            get {
                return ResourceManager.GetString("SubstituteMultipleClassesTitle", resourceCulture);
            }
        }
        
        internal static string SubstituteConstructorArgumentsForInterfaceDescription {
            get {
                return ResourceManager.GetString("SubstituteConstructorArgumentsForInterfaceDescription", resourceCulture);
            }
        }
        
        internal static string SubstituteConstructorArgumentsForInterfaceMessageFormat {
            get {
                return ResourceManager.GetString("SubstituteConstructorArgumentsForInterfaceMessageFormat", resourceCulture);
            }
        }
        
        internal static string SubstituteConstructorArgumentsForInterfaceTitle {
            get {
                return ResourceManager.GetString("SubstituteConstructorArgumentsForInterfaceTitle", resourceCulture);
            }
        }
        
        internal static string SubstituteConstructorArgumentsForDelegateDescription {
            get {
                return ResourceManager.GetString("SubstituteConstructorArgumentsForDelegateDescription", resourceCulture);
            }
        }
        
        internal static string SubstituteConstructorArgumentsForDelegateMessageFormat {
            get {
                return ResourceManager.GetString("SubstituteConstructorArgumentsForDelegateMessageFormat", resourceCulture);
            }
        }
        
        internal static string SubstituteConstructorArgumentsForDelegateTitle {
            get {
                return ResourceManager.GetString("SubstituteConstructorArgumentsForDelegateTitle", resourceCulture);
            }
        }
        
        internal static string NonVirtualReceivedSetupSpecificationDescription {
            get {
                return ResourceManager.GetString("NonVirtualReceivedSetupSpecificationDescription", resourceCulture);
            }
        }
        
        internal static string NonVirtualReceivedSetupSpecificationTitle {
            get {
                return ResourceManager.GetString("NonVirtualReceivedSetupSpecificationTitle", resourceCulture);
            }
        }
        
        internal static string NonVirtualWhenSetupSpecificationDescription {
            get {
                return ResourceManager.GetString("NonVirtualWhenSetupSpecificationDescription", resourceCulture);
            }
        }
        
        internal static string NonVirtualWhenSetupSpecificationTitle {
            get {
                return ResourceManager.GetString("NonVirtualWhenSetupSpecificationTitle", resourceCulture);
            }
        }
        
        internal static string ReEntrantSubstituteCallDescription {
            get {
                return ResourceManager.GetString("ReEntrantSubstituteCallDescription", resourceCulture);
            }
        }
        
        internal static string ReEntrantSubstituteCallTitle {
            get {
                return ResourceManager.GetString("ReEntrantSubstituteCallTitle", resourceCulture);
            }
        }
        
        internal static string CallInfoArgumentOutOfRangeDescription {
            get {
                return ResourceManager.GetString("CallInfoArgumentOutOfRangeDescription", resourceCulture);
            }
        }
        
        internal static string CallInfoArgumentOutOfRangeMessageFormat {
            get {
                return ResourceManager.GetString("CallInfoArgumentOutOfRangeMessageFormat", resourceCulture);
            }
        }
        
        internal static string CallInfoArgumentOutOfRangeTitle {
            get {
                return ResourceManager.GetString("CallInfoArgumentOutOfRangeTitle", resourceCulture);
            }
        }
        
        internal static string CallInfoCouldNotConvertParameterAtPositionDescription {
            get {
                return ResourceManager.GetString("CallInfoCouldNotConvertParameterAtPositionDescription", resourceCulture);
            }
        }
        
        internal static string CallInfoCouldNotConvertParameterAtPositionMessageFormat {
            get {
                return ResourceManager.GetString("CallInfoCouldNotConvertParameterAtPositionMessageFormat", resourceCulture);
            }
        }
        
        internal static string CallInfoCouldNotConvertParameterAtPositionTitle {
            get {
                return ResourceManager.GetString("CallInfoCouldNotConvertParameterAtPositionTitle", resourceCulture);
            }
        }
        
        internal static string CallInfoCouldNotFindArgumentToThisCallDescription {
            get {
                return ResourceManager.GetString("CallInfoCouldNotFindArgumentToThisCallDescription", resourceCulture);
            }
        }
        
        internal static string CallInfoCouldNotFindArgumentToThisCallMessageFormat {
            get {
                return ResourceManager.GetString("CallInfoCouldNotFindArgumentToThisCallMessageFormat", resourceCulture);
            }
        }
        
        internal static string CallInfoCouldNotFindArgumentToThisCallTitle {
            get {
                return ResourceManager.GetString("CallInfoCouldNotFindArgumentToThisCallTitle", resourceCulture);
            }
        }
        
        internal static string CallInfoMoreThanOneArgumentOfTypeDescription {
            get {
                return ResourceManager.GetString("CallInfoMoreThanOneArgumentOfTypeDescription", resourceCulture);
            }
        }
        
        internal static string CallInfoMoreThanOneArgumentOfTypeMessageFormat {
            get {
                return ResourceManager.GetString("CallInfoMoreThanOneArgumentOfTypeMessageFormat", resourceCulture);
            }
        }
        
        internal static string CallInfoMoreThanOneArgumentOfTypeTitle {
            get {
                return ResourceManager.GetString("CallInfoMoreThanOneArgumentOfTypeTitle", resourceCulture);
            }
        }
        
        internal static string CallInfoArgumentSetWithIncompatibleValueDescription {
            get {
                return ResourceManager.GetString("CallInfoArgumentSetWithIncompatibleValueDescription", resourceCulture);
            }
        }
        
        internal static string CallInfoArgumentSetWithIncompatibleValueMessageFormat {
            get {
                return ResourceManager.GetString("CallInfoArgumentSetWithIncompatibleValueMessageFormat", resourceCulture);
            }
        }
        
        internal static string CallInfoArgumentSetWithIncompatibleValueTitle {
            get {
                return ResourceManager.GetString("CallInfoArgumentSetWithIncompatibleValueTitle", resourceCulture);
            }
        }
        
        internal static string CallInfoArgumentIsNotOutOrRefDescription {
            get {
                return ResourceManager.GetString("CallInfoArgumentIsNotOutOrRefDescription", resourceCulture);
            }
        }
        
        internal static string CallInfoArgumentIsNotOutOrRefMessageFormat {
            get {
                return ResourceManager.GetString("CallInfoArgumentIsNotOutOrRefMessageFormat", resourceCulture);
            }
        }
        
        internal static string CallInfoArgumentIsNotOutOrRefTitle {
            get {
                return ResourceManager.GetString("CallInfoArgumentIsNotOutOrRefTitle", resourceCulture);
            }
        }
        
        internal static string ConflictingArgumentAssignmentsDescription {
            get {
                return ResourceManager.GetString("ConflictingArgumentAssignmentsDescription", resourceCulture);
            }
        }
        
        internal static string ConflictingArgumentAssignmentsMessageFormat {
            get {
                return ResourceManager.GetString("ConflictingArgumentAssignmentsMessageFormat", resourceCulture);
            }
        }
        
        internal static string ConflictingArgumentAssignmentsTitle {
            get {
                return ResourceManager.GetString("ConflictingArgumentAssignmentsTitle", resourceCulture);
            }
        }
        
        internal static string NonSubstitutableMemberArgumentMatcherUsageDescription {
            get {
                return ResourceManager.GetString("NonSubstitutableMemberArgumentMatcherUsageDescription", resourceCulture);
            }
        }
        
        internal static string NonSubstitutableMemberArgumentMatcherUsageMessageFormat {
            get {
                return ResourceManager.GetString("NonSubstitutableMemberArgumentMatcherUsageMessageFormat", resourceCulture);
            }
        }
        
        internal static string NonSubstitutableMemberArgumentMatcherUsageTitle {
            get {
                return ResourceManager.GetString("NonSubstitutableMemberArgumentMatcherUsageTitle", resourceCulture);
            }
        }
        
        internal static string ReceivedUsedInReceivedInOrderDescription {
            get {
                return ResourceManager.GetString("ReceivedUsedInReceivedInOrderDescription", resourceCulture);
            }
        }
        
        internal static string ReceivedUsedInReceivedInOrderMessageFormat {
            get {
                return ResourceManager.GetString("ReceivedUsedInReceivedInOrderMessageFormat", resourceCulture);
            }
        }
        
        internal static string ReceivedUsedInReceivedInOrderTitle {
            get {
                return ResourceManager.GetString("ReceivedUsedInReceivedInOrderTitle", resourceCulture);
            }
        }
    }
}
